"""add user last_login_at

Revision ID: 729bf7263724
Revises: 
Create Date: 2026-07-15 04:36:12.148500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729bf7263724'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='最后登录时间'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_login_at')

    # ### end Alembic commands ###
